title: when shit gets real
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3136201
  brandStrength: 0.8978494
  lightness: 0.1702509
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.8327768
typography_spectrum: 0.6433692
description: tech & gadgets
layout_spectrum: 0.2849462
name: unreal paralysis
